version: '3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tenpo
    ports:
      - "54320:5432"
  app:
    image: com.tenpo.challenge:0.0.1-SNAPSHOT
    build: .
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tenpo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JAVA_OPTS=-Xms256m -Xmx512m -XX:+UseG1GC
    ports:
      - "8080:8080"